
DROP TABLE IF EXISTS USER;
CREATE TABLE USER (ID VARCHAR PRIMARY KEY, SEX VARCHAR, NICKNAME VARCHAR, PROFILE_PHOTO VARCHAR, BIRTHDAY VARCHAR);

INSERT INTO USER (ID, SEX, NICKNAME, PROFILE_PHOTO, BIRTHDAY) VALUES ('scatter1', 'F', '스캐터','http://www.scatter.com/image.jpg','19850401');
INSERT INTO USER (ID, SEX, NICKNAME, PROFILE_PHOTO, BIRTHDAY) VALUES ('scatter2', 'F', '이화수','http://www.scatter.com/image.jpg','19990101');
INSERT INTO USER (ID, SEX, NICKNAME, PROFILE_PHOTO, BIRTHDAY) VALUES ('scatter3', 'M', '아싸','http://www.scatter.com/image.jpg','19550101');
INSERT INTO USER (ID, SEX, NICKNAME, PROFILE_PHOTO, BIRTHDAY) VALUES ('scatter4', 'M', '인싸','http://www.scatter.com/image.jpg','19880808');


DROP TABLE IF EXISTS COMMUNITY_BASE;
CREATE TABLE COMMUNITY_BASE(ID INT PRIMARY KEY AUTO_INCREMENT, UPR_ID INT, DEPTH INT, TITLE VARCHAR, CONTENTS VARCHAR, HIT INT, LIKED INT, DISLIKED INT, REG_ID VARCHAR);

INSERT INTO COMMUNITY_BASE(DEPTH, TITLE, CONTENTS, HIT, LIKED, DISLIKED, REG_ID) VALUES (0, '제 마음이 식은걸까요?', '제 마음이 식은걸까요?제 마음이 식은걸까요?제 마음이 식은걸까요?제 마음이 식은걸까요?제 마음이 식은걸까요?',10,5 ,0,'scatter1');
INSERT INTO COMMUNITY_BASE(DEPTH, TITLE, CONTENTS, HIT, LIKED, DISLIKED, REG_ID) VALUES (0, '속옷 선물 무슨의미죠?', '속옷 선물 무슨의미죠?속옷 선물 무슨의미죠?속옷 선물 무슨의미죠?속옷 선물 무슨의미죠?',11,6 ,1,'scatter2');
INSERT INTO COMMUNITY_BASE(DEPTH, TITLE, CONTENTS, HIT, LIKED, DISLIKED, REG_ID) VALUES (0, '남자친구 사랑하는것같아요', '남자친구 사랑하는것같아요남자친구 사랑하는것같아요남자친구 사랑하는것같아요남자친구 사랑하는것같아요',12,7 ,2,'scatter3');
INSERT INTO COMMUNITY_BASE(DEPTH, TITLE, CONTENTS, HIT, LIKED, DISLIKED, REG_ID) VALUES (0, '헤어진 남친', '헤어진 남친헤어진 남친헤어진 남친헤어진 남친헤어진 남친헤어진 남친헤어진 남친',13,8 ,3,'scatter4');
INSERT INTO COMMUNITY_BASE(DEPTH, TITLE, CONTENTS, HIT, LIKED, DISLIKED, REG_ID) VALUES (0, '헤어진지 한달뒤', '헤어진지 한달뒤 헤어진지 한달뒤 헤어진지 한달뒤 헤어진지 한달뒤 헤어진지 한달뒤',13,8 ,3,'scatter1');

INSERT INTO COMMUNITY_BASE(UPR_ID, DEPTH, CONTENTS, HIT, LIKED, DISLIKED, REG_ID) VALUES (1, 1, '네 식었어요', 0, 5, 10,'scatter1');
INSERT INTO COMMUNITY_BASE(UPR_ID, DEPTH, CONTENTS, HIT, LIKED, DISLIKED, REG_ID) VALUES (1, 1, '식었구나~~', 0, 99, 4,'scatter2');
INSERT INTO COMMUNITY_BASE(UPR_ID, DEPTH, CONTENTS, HIT, LIKED, DISLIKED, REG_ID) VALUES (1, 1, '식었다구요!', 0, 20, 3,'scatter3');
INSERT INTO COMMUNITY_BASE(UPR_ID, DEPTH, CONTENTS, HIT, LIKED, DISLIKED, REG_ID) VALUES (2, 1, '좋은의미죠', 0, 5, 10,'scatter1');
INSERT INTO COMMUNITY_BASE(UPR_ID, DEPTH, CONTENTS, HIT, LIKED, DISLIKED, REG_ID) VALUES (2, 1, '안좋은의미', 0, 99, 4,'scatter2');
INSERT INTO COMMUNITY_BASE(UPR_ID, DEPTH, CONTENTS, HIT, LIKED, DISLIKED, REG_ID) VALUES (2, 1, '헤어지자는 의미', 0, 20, 3,'scatter3');
INSERT INTO COMMUNITY_BASE(UPR_ID, DEPTH, CONTENTS, HIT, LIKED, DISLIKED, REG_ID) VALUES (3, 1, '저도 사랑해요', 0, 5, 10,'scatter1');
INSERT INTO COMMUNITY_BASE(UPR_ID, DEPTH, CONTENTS, HIT, LIKED, DISLIKED, REG_ID) VALUES (3, 1, '많이 사랑하세요', 0, 99, 4,'scatter2');
INSERT INTO COMMUNITY_BASE(UPR_ID, DEPTH, CONTENTS, HIT, LIKED, DISLIKED, REG_ID) VALUES (3, 1, '나도 사랑해', 0, 20, 3,'scatter3');
INSERT INTO COMMUNITY_BASE(UPR_ID, DEPTH, CONTENTS, HIT, LIKED, DISLIKED, REG_ID) VALUES (4, 1, '헤어진여친', 0, 5, 10,'scatter1');
INSERT INTO COMMUNITY_BASE(UPR_ID, DEPTH, CONTENTS, HIT, LIKED, DISLIKED, REG_ID) VALUES (4, 1, '헤어지세요', 0, 99, 4,'scatter2');
INSERT INTO COMMUNITY_BASE(UPR_ID, DEPTH, CONTENTS, HIT, LIKED, DISLIKED, REG_ID) VALUES (4, 1, '얼릉 헤어지세요', 0, 20, 3,'scatter3');
INSERT INTO COMMUNITY_BASE(UPR_ID, DEPTH, CONTENTS, HIT, LIKED, DISLIKED, REG_ID) VALUES (5, 1, '저도 한달', 0, 5, 10,'scatter1');
INSERT INTO COMMUNITY_BASE(UPR_ID, DEPTH, CONTENTS, HIT, LIKED, DISLIKED, REG_ID) VALUES (5, 1, '난 두달', 0, 99, 4,'scatter2');
INSERT INTO COMMUNITY_BASE(UPR_ID, DEPTH, CONTENTS, HIT, LIKED, DISLIKED, REG_ID) VALUES (5, 1, '난 세달', 0, 20, 3,'scatter3');

INSERT INTO COMMUNITY_BASE(UPR_ID, DEPTH, CONTENTS, HIT, LIKED, DISLIKED, REG_ID) VALUES (7, 2, '그렇군요', 0, 2, 1,'scatter4');
INSERT INTO COMMUNITY_BASE(UPR_ID, DEPTH, CONTENTS, HIT, LIKED, DISLIKED, REG_ID) VALUES (10, 2, '그런가요?', 0, 2, 1,'scatter4');
INSERT INTO COMMUNITY_BASE(UPR_ID, DEPTH, CONTENTS, HIT, LIKED, DISLIKED, REG_ID) VALUES (13, 2, '감사합니다.', 0, 2, 1,'scatter4');
INSERT INTO COMMUNITY_BASE(UPR_ID, DEPTH, CONTENTS, HIT, LIKED, DISLIKED, REG_ID) VALUES (16, 2, '오호~', 0, 2, 1,'scatter4');
INSERT INTO COMMUNITY_BASE(UPR_ID, DEPTH, CONTENTS, HIT, LIKED, DISLIKED, REG_ID) VALUES (19, 2, '아하~', 0, 2, 1,'scatter4');
